# Generated by Django 3.0.6 on 2020-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
