# Generated by Django 3.0.6 on 2020-05-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('gameproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameproject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
