# Generated by Django 3.0.6 on 2020-05-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('reward', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameproject.GameProject')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Tier')),
            ],
        ),
    ]
