# Generated by Django 3.0.6 on 2020-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='stripe_subscription_id',
            field=models.CharField(default='', max_length=254),
        ),
    ]
