# Generated by Django 3.0.6 on 2020-05-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameproject', '0002_auto_20200515_1220'),
        ('subscription', '0002_tier_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('game_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameproject.GameProject')),
            ],
        ),
    ]
