# Generated by Django 3.0.6 on 2020-05-19 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameproject', '__first__'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('donation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameproject.Donation')),
                ('game_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameproject.GameProject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='profiles.Profile')),
            ],
        ),
    ]
