# Generated by Django 3.0.6 on 2020-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('SP', 'Send Payment'), ('PA', 'Paid'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
