# Generated by Django 3.0.6 on 2020-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('PS', 'Payment Sent'), ('FA', 'Failed'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
