# Generated by Django 3.0.6 on 2020-05-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200529_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid')], default='PE', max_length=2),
        ),
    ]
