# Generated by Django 3.0.6 on 2020-05-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameproject', '0002_auto_20200515_1220'),
        ('checkout', '0004_auto_20200515_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='game_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameproject.GameProject'),
        ),
    ]
